name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:

  test_tailwindcss:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [17.6.0]
        change_cmd: ['cp', 'mv']
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    name: ${{ matrix.change_cmd }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup
        run: |
          npm install
          npx pm2 start ecosystem.config.js
          npx pm2 ls
          sleep 3
          echo "Initial output"
          echo "${{ github.workspace }}"
          /bin/bash -c "grep 'btn-cool' dist/output.css || echo EMPTY"
          echo "Setup done"

      - if: always()
        name: Test 1
        run: |
          ${{ matrix.change_cmd }} templates/tailwind.css.1 src/tailwind.css
          sleep 3
          echo "## start after ${{ matrix.change_cmd }} t 1"
          grep 'btn-cool' dist/output.css
          echo "## end after ${{ matrix.change_cmd }} t 1"
          ${{ matrix.change_cmd }} templates/index.html.1 src/index.html
          sleep 3
          echo "## start after ${{ matrix.change_cmd }}i 1"
          grep 'btn-cool' dist/output.css
          echo "## end after ${{ matrix.change_cmd }}i 1"
          grep 'btn-cool-1' dist/output.css

      - if: always()
        name: Test 2
        run: |
          ${{ matrix.change_cmd }} templates/tailwind.css.2 src/tailwind.css
          sleep 3
          echo "## start after ${{ matrix.change_cmd }} t 2"
          grep 'btn-cool' dist/output.css
          echo "## end after ${{ matrix.change_cmd }} t 2"
          ${{ matrix.change_cmd }} templates/index.html.2 src/index.html
          sleep 3
          echo "## start after ${{ matrix.change_cmd }}i 2"
          grep 'btn-cool' dist/output.css
          echo "## end after ${{ matrix.change_cmd }}i 2"
          grep 'btn-cool-2' dist/output.css

      - if: always()
        name: Logs
        run: npx pm2 log --nostream --lines 1000 --timestamp tailwindcss-watch

      - if: always()
        run: cat dist/output.css

